version: "3.8"

services:
  telegram-api:
    build: .
    ports:
      - "8020:8000"
    env_file:
      - .env
    restart: always
    volumes:
      - ./user_session.session:/app/user_session.session  # 👈 монтируем .session внутрь контейнера
